/**
 * Off-chain document generation for rental agreements and purchase contracts.
 * Based on verified user/transaction data. Output is structured text; can be extended to PDF.
 */

function formatEth(wei) {
  if (wei == null || wei === undefined) return "0";
  const n = BigInt(wei);
  const div = BigInt(1e18);
  const whole = n / div;
  const frac = n % div;
  return frac === 0n ? whole.toString() : `${whole}.${frac.toString().padStart(18, "0").replace(/0+$/, "")}`;
}

function formatDate(ts) {
  if (ts == null) return "[Start Date]";
  const d = new Date(Number(ts) * 1000);
  return d.toISOString().split("T")[0];
}

exports.generateRentalAgreement = function (opts) {
  const {
    tokenId,
    landlordAddress,
    tenantAddress,
    rentWeiPerPeriod,
    periodSeconds,
    startTime,
    propertyTitle = "Property",
  } = opts || {};
  const rentEth = formatEth(rentWeiPerPeriod);
  const periodDays = periodSeconds ? Math.round(Number(periodSeconds) / 86400) : "[Period]";
  const start = formatDate(startTime);
  const title = `Rental Agreement – ${propertyTitle} (Token #${tokenId ?? "—"})`;
  const body = `
RENTAL AGREEMENT

${title}

1. Parties
   - Landlord: ${landlordAddress ?? "[Landlord Address]"}
   - Tenant: ${tenantAddress ?? "[Tenant Address]"}

2. Property
   - On-chain representation: Property NFT Token ID ${tokenId ?? "—"}
   - Description: ${propertyTitle}

3. Term and Rent
   - Start date: ${start}
   - Rent per period: ${rentEth} ETH
   - Billing period: ${periodDays} days

4. Payment
   - Rent is paid on-chain via the RealFraction RentalManager contract.
   - Each period's rent is due by the next payment due time recorded on-chain.

5. Governing contract
   - This agreement is backed by the on-chain rental agreement in the RealFraction RentalManager.
   - In case of conflict, on-chain state prevails.

Generated by RealFraction. This document is for reference; verify on-chain state for authority.
`.trim();
  return { title, body, format: "text" };
};

exports.generatePurchaseContract = function (opts) {
  const { tokenId, sellerAddress, buyerAddress, priceWei, propertyTitle = "Property" } = opts || {};
  const priceEth = formatEth(priceWei);
  const title = `Purchase Contract – ${propertyTitle} (Token #${tokenId ?? "—"})`;
  const body = `
PURCHASE CONTRACT

${title}

1. Parties
   - Seller: ${sellerAddress ?? "[Seller Address]"}
   - Buyer: ${buyerAddress ?? "[Buyer Address]"}

2. Property
   - On-chain representation: Property NFT Token ID ${tokenId ?? "—"}
   - Description: ${propertyTitle}

3. Purchase Price
   - Total price: ${priceEth} ETH

4. Transfer
   - Ownership of the Property NFT shall be transferred on-chain via the RealFraction Marketplace (or equivalent) upon receipt of the purchase price.
   - Title passes upon successful on-chain transfer.

5. Governing contract
   - This contract is evidenced by the on-chain transaction. On-chain state is authoritative.

Generated by RealFraction. Verify on-chain transaction for authority.
`.trim();
  return { title, body, format: "text" };
};
